#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
// Suppress warnings generated by bindgen's output in Rust 2024 edition
#![allow(unsafe_op_in_unsafe_fn)]
// Suppress clippy lints for auto-generated code
#![allow(clippy::ptr_offset_with_cast)]
#![allow(clippy::upper_case_acronyms)]
#![allow(clippy::useless_transmute)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
